Uproot science image updates
ssl-hep/science-images pull request #8
Opened 2024-06-27 22:55 UTC by ponyisi

uproot 5.1.2 -> 5.3.8 (this is actually quite important since it should fix an occasional bug we see in SXLite reading directly from dCache)
awkward 2.5.0 -> 2.6.6
dask-awkward 2023.11.3 -> 2024.6.0
vector 1.1.1.post1 -> 1.4.1
pyarrow 14.0.1 -> 16.1.0
xrootd 5.4.3 -> 5.6.9
miniconda3 base image 4.12.0 -> 24.5.0

2024-06-27 23:21 UTC, matthewfeickert requested changes

2024-06-27 23:21 UTC, matthewfeickert commented on uproot/requirements.txt
> +uproot==5.3.8
```suggestion
uproot==5.3.9
```

`uproot` `v5.3.9` _just_ came out today. https://github.com/scikit-hep/uproot5/releases/tag/v5.3.9

2024-06-27 23:36 UTC, matthewfeickert approved these changes

2024-07-01 20:14 UTC, ponyisi commented
Attn @BenGalewsky @ivukotic

2024-07-01 20:42 UTC, BenGalewsky approved these changes
Thanks for the refresh

2024-07-01 20:42 UTC, merged